/**
 * Half-Life 2 (Xbox) - Recompiled Game Entry Point
 *
 * Hosts the recompiled hl2_xbox.xbe. Boot order matters and is the same one
 * the other titles in this family use:
 *
 *   1. load the XBE                     (the recompiled code reads its own
 *                                        .rdata/.data out of the mapped image)
 *   2. map the Xbox memory layout       at the original virtual addresses
 *   3. bring up the MCPX APU            DirectSound spins on the audio DSP,
 *                                        and on Wreckless the whole engine
 *                                        init sat behind DirectSoundCreate
 *                                        succeeding -- so audio is not
 *                                        optional even when chasing pixels
 *   4. kernel replacement + thunk table
 *   5. set the guest stack pointer
 *   6. jump to the recompiled entry point
 *
 * XBE details (retail, 2005-10-14):
 *   Title:       Half-Life 2
 *   Title ID:    0x45410091
 *   Base addr:   0x00010000
 *   Entry point: 0x0059C612
 *   Code size:   6031 KB (.text) -- engine + client + server in one image
 *   Sections:    10, XDK 1.0.5849, D3D8LTCG
 *   Kernel imports: 124
 */

#include <windows.h>
#include <dbghelp.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "recomp_icall_feedback.h"
#include "../kernel/kernel.h"
#include "../kernel/xbox_memory_layout.h"
#include "../d3d/d3d8_xbox.h"

/* RECOMP_TLS is required: the runtime defines these thread-local, and a plain
 * extern resolves to the image's TLS template rather than this thread's copy,
 * which starts the guest with every register at zero. */
extern RECOMP_TLS uint32_t g_eax, g_ecx, g_edx, g_esp;
extern RECOMP_TLS uint32_t g_ebx, g_esi, g_edi;
extern ptrdiff_t g_xbox_mem_offset;

extern void xbe_entry_point(void);

/* Generated by tools.recomp into recomp_dispatch.c. */
int recomp_dispatch_init(void);

#define HL2_XBE_DEFAULT  "game\\hl2_xbox.xbe"

/* The disc ships GameMedia/ and LoaderMedia/, but the title does not read them
 * from the disc: default.xbe (the loader) copies the .xz_ archives to
 * Z:\hl2\hl2x\*.xzp on the HDD first, per LoaderMedia/install.txt, and the
 * game then opens that path. So the file layer is pointed at game/ and the
 * Z: mapping is what has to line up -- see docs/ for where that stands. */
#define HL2_GAME_DIR     "game"
#define HL2_SAVE_DIR     "saves"

static const char *g_xbe_path;

static BOOL load_xbe(const char *path, void **out_data, size_t *out_size)
{
    FILE *f = fopen(path, "rb");
    long size;
    void *data;

    if (!f) {
        fprintf(stderr, "Cannot open XBE: %s\n", path);
        return FALSE;
    }
    fseek(f, 0, SEEK_END);
    size = ftell(f);
    fseek(f, 0, SEEK_SET);
    if (size <= 0) {
        fclose(f);
        return FALSE;
    }
    if (!(data = malloc((size_t)size))) {
        fclose(f);
        return FALSE;
    }
    if (fread(data, 1, (size_t)size, f) != (size_t)size) {
        free(data);
        fclose(f);
        return FALSE;
    }
    fclose(f);
    *out_data = data;
    *out_size = (size_t)size;
    return TRUE;
}


/* Report a host fault with the guest state that caused it.
 *
 * Recompiled code faults as ordinary native code, so without this a crash is
 * just "Segmentation fault" with nothing to act on. The guest registers are
 * globals, so they can be printed directly, and the faulting address minus
 * g_xbox_mem_offset says which guest address was touched -- which is what
 * distinguishes a null dereference from a wild pointer. */
/* Name the host address a fault happened at.
 *
 * Recompiled code faults as ordinary native code, so the exception record
 * carries a host address and nothing else -- there is no guest program
 * counter to report. But every generated function is a real symbol in the
 * image (sub_005A03C0 and so on), so the linker's PDB already holds the map
 * from host address back to guest function. Asking dbghelp turns 'access
 * violation at 0x142CD9D25', which changes every build and names nothing,
 * into the guest function that faulted.
 */
static void print_host_symbol(void *addr)
{
    /* SYMBOL_INFO is variable-length: the name is written past the struct,
     * so it must be over-allocated with MaxNameLen set to the slack. */
    char buf[sizeof(SYMBOL_INFO) + 256];
    SYMBOL_INFO *sym = (SYMBOL_INFO *)buf;
    DWORD64 disp = 0;

    memset(buf, 0, sizeof(buf));
    sym->SizeOfStruct = sizeof(SYMBOL_INFO);
    sym->MaxNameLen = 255;

    if (SymFromAddr(GetCurrentProcess(), (DWORD64)(uintptr_t)addr, &disp, sym))
        fprintf(stderr, "  in %s+0x%llX\n", sym->Name,
                (unsigned long long)disp);
    else
        fprintf(stderr, "  in <no symbol; keep hl2.pdb beside the exe>\n");
}

/* Guest backtrace.
 *
 * Recompiled code faults as native code, so the host address in the report
 * above names a generated C function and nothing more -- it does not say
 * which guest function, and there is no guest program counter to consult.
 * But every lifted call pushes its guest return address onto the guest
 * stack before jumping, so the stack still holds the call chain. Scanning
 * up from esp for values inside the code sections recovers it.
 *
 * ponytail: a scan, not a frame walk -- these are FPO frames with no
 * reliable ebp chain, so there is nothing to walk. It over-reports (stale
 * addresses from previous calls linger below esp) but it is enough to name
 * the guest function, which is the whole question at a fault.
 */
static void print_guest_stack(void)
{
    if (g_xbox_mem_offset && g_esp) {
        const uint32_t *sp =
            (const uint32_t *)((uintptr_t)g_xbox_mem_offset + g_esp);
        int shown = 0, i;
        fprintf(stderr, "  guest stack (return addresses, innermost first):\n");
        for (i = 0; i < 256 && shown < 24; i++) {
            uint32_t v = sp[i];
            if (v > g_xbox_code_lo && v < g_xbox_code_hi) {
                fprintf(stderr, "    [esp+%-4d] 0x%08X\n",
                        i * 4, v);
                shown++;
            }
        }
        if (!shown)
            fprintf(stderr, "    (none -- stack pointer is not in guest memory)\n");
    }
}

/* Hardware write watchpoint on a guest address.
 *
 * When a value is correct at one point and wrong at the next, the question is
 * who wrote it, and reading candidate code does not answer that -- the writer
 * is usually not among the functions you suspected. x86 debug registers do:
 * DR0 holds the address, DR7 arms a 4-byte write breakpoint, and the trap
 * arrives in the same handler that already turns a host RIP into a guest
 * function name.
 *
 * Per-thread, so this has to be called on the guest thread. The address is a
 * guest VA and gets mapped through g_xbox_mem_offset.
 */
static uintptr_t g_watch_host;

void recomp_watch_guest_write(uint32_t guest_va)
{
    CONTEXT ctx;

    if (!g_xbox_mem_offset || g_watch_host)
        return;                          /* one at a time is enough */

    g_watch_host = (uintptr_t)g_xbox_mem_offset + guest_va;
    memset(&ctx, 0, sizeof(ctx));
    ctx.ContextFlags = CONTEXT_DEBUG_REGISTERS;
    if (!GetThreadContext(GetCurrentThread(), &ctx))
        return;
    ctx.Dr0 = (DWORD64)g_watch_host;
    /* L0 | (RW0 = 01: write) | (LEN0 = 11: four bytes) */
    ctx.Dr7 = (DWORD64)((1u << 0) | (1u << 16) | (3u << 18));
    ctx.ContextFlags = CONTEXT_DEBUG_REGISTERS;
    if (SetThreadContext(GetCurrentThread(), &ctx))
        fprintf(stderr, "[WATCH] armed on guest 0x%08X (host %p)\n",
                guest_va, (void *)g_watch_host);
    fflush(stderr);
}

/* Say where the guest is stuck.

 * A hang gives you nothing: no fault, no output, and with a tight loop in
 * lifted code there are no kernel calls or indirect calls to count either. The
 * fault handler already knows how to turn a host address into a guest function
 * name; this is the same trick applied on a timer instead of on a trap.
 *
 * Suspend the guest thread, sample its RIP, name it, resume. Repeated a few
 * times so a slow loop reads differently from a stuck one -- the same symbol
 * every sample is a spin, a moving one is just slow.
 *
 * ponytail: sampling one thread on a timer, not a profiler. The question at a
 * hang is "which function", and one address answers it.
 */
static HANDLE g_guest_thread;

static DWORD WINAPI hang_watchdog(LPVOID arg)
{
    unsigned seconds = (unsigned)(uintptr_t)arg;
    int sample;

    for (sample = 0; sample < 4; sample++) {
        CONTEXT ctx;

        Sleep(seconds * 1000);
        memset(&ctx, 0, sizeof(ctx));
        ctx.ContextFlags = CONTEXT_CONTROL;

        if (SuspendThread(g_guest_thread) == (DWORD)-1)
            return 0;
        if (GetThreadContext(g_guest_thread, &ctx)) {
            fprintf(stderr, "\n[HANG] sample %d after %us:\n",
                    sample + 1, (sample + 1) * seconds);
            /* Only the sampled RIP is readable from here. The guest
             * registers are RECOMP_TLS, so reading them on this thread
             * would report the watchdog own zeroed copies rather than
             * the guest state -- worse than printing nothing, because
             * it looks like an answer. The symbol is the answer. */
            print_host_symbol((void *)(uintptr_t)ctx.Rip);
            fflush(stderr);
        }
        ResumeThread(g_guest_thread);
    }
    return 0;
}

/* Start only when asked: RECOMP_HANG_WATCHDOG=<seconds>. */
static void hang_watchdog_start(void)
{
    const char *spec = getenv("RECOMP_HANG_WATCHDOG");
    unsigned seconds;

    if (!spec || (seconds = (unsigned)atoi(spec)) == 0)
        return;
    if (!DuplicateHandle(GetCurrentProcess(), GetCurrentThread(),
                         GetCurrentProcess(), &g_guest_thread,
                         0, FALSE, DUPLICATE_SAME_ACCESS))
        return;
    CloseHandle(CreateThread(NULL, 0, hang_watchdog,
                             (LPVOID)(uintptr_t)seconds, 0, NULL));
}

static unsigned g_fault_reports;

static LONG CALLBACK veh_handler(PEXCEPTION_POINTERS ep)
{
    const EXCEPTION_RECORD *er = ep->ExceptionRecord;

    if (er->ExceptionCode == EXCEPTION_SINGLE_STEP && g_watch_host) {
        static unsigned hits;
        if (hits++ < 8) {
            fprintf(stderr, "\n[WATCH] write to guest 0x%08X\n",
                    (uint32_t)(g_watch_host - (uintptr_t)g_xbox_mem_offset));
            print_host_symbol((void *)(uintptr_t)ep->ContextRecord->Rip);
            fflush(stderr);
        }
        ep->ContextRecord->Dr6 = 0;
        return EXCEPTION_CONTINUE_EXECUTION;
    }

    if (er->ExceptionCode != EXCEPTION_ACCESS_VIOLATION)
        return EXCEPTION_CONTINUE_SEARCH;

    /* Cap the dumps. The static-init walk now continues past a constructor
     * that faults, so a systematic problem produces thousands of these and
     * the useful part -- the first few, and the final counts -- scrolls away.
     * The handler still returns CONTINUE_SEARCH every time, so recovery is
     * unaffected; only the printing stops. */
    if (++g_fault_reports > 6) {
        if (g_fault_reports == 7)
            fprintf(stderr, "\n[FAULT] further faults not reported\n");
        return EXCEPTION_CONTINUE_SEARCH;
    }

    fprintf(stderr, "\n[FAULT] access violation at host %p\n",
            er->ExceptionAddress);
    print_host_symbol(er->ExceptionAddress);
    if (er->NumberParameters >= 2) {
        uintptr_t addr = (uintptr_t)er->ExceptionInformation[1];
        fprintf(stderr, "  %s address host 0x%p",
                er->ExceptionInformation[0] ? "write to" : "read from",
                (void *)addr);
        if (g_xbox_mem_offset &&
            addr >= (uintptr_t)g_xbox_mem_offset &&
            addr < (uintptr_t)g_xbox_mem_offset + 0x10000000u)
            fprintf(stderr, "  = guest 0x%08X",
                    (uint32_t)(addr - (uintptr_t)g_xbox_mem_offset));
        fprintf(stderr, "\n");
    }
    fprintf(stderr, "  guest regs: eax=%08X ecx=%08X edx=%08X ebx=%08X\n"
                    "              esp=%08X esi=%08X edi=%08X\n",
            g_eax, g_ecx, g_edx, g_ebx, g_esp, g_esi, g_edi);
    print_guest_stack();

    /* The heap free-list bucket the allocator was walking.
     *
     * sub_0059FC74 indexes buckets as [esi + edi*8 + 0x180], and an empty one
     * must hold Flink = Blink = its own address. Printing it says whether
     * RtlCreateHeap ever initialised the list or whether it was corrupted
     * later, which are different bugs. */
    if (g_xbox_mem_offset && g_esi && g_edi < 0x80) {
        uint32_t bucket = g_esi + g_edi * 8 + 0x180;
        const uint32_t *p = (const uint32_t *)((uintptr_t)g_xbox_mem_offset + bucket);
        const uint32_t *hdr = (const uint32_t *)((uintptr_t)g_xbox_mem_offset + g_esi);
        const uint32_t *b0 = (const uint32_t *)((uintptr_t)g_xbox_mem_offset + g_esi + 0x180);
        fprintf(stderr, "  heap bucket %u @0x%08X: Flink=%08X Blink=%08X"
                        " (expect both = %08X)\n",
                g_edi, bucket, p[0], p[1], bucket);
        /* 0xEEFFEEFF is the signature RtlCreateHeap writes at +0x10 just before
         * it initialises the free lists. Present means that header block ran and
         * something cleared the lists afterwards; absent means it never ran.
         * Bucket 0 says how far the initialisation loop got. */
        fprintf(stderr, "  heap hdr @0x%08X: sig=%08X (expect EEFFEEFF)  "
                        "bucket0 Flink=%08X (expect %08X)\n",
                g_esi, hdr[4], b0[0], g_esi + 0x180);
        /* Where did RtlCreateHeap actually write its header?
         *
         * The initialisation loop and the allocator both index from what should
         * be the same heap base. If the signature turns up at some other
         * address they disagree, which is a different bug from the loop never
         * running at all. Scan the arena for it. */
        {
            const uint32_t *scan = (const uint32_t *)
                ((uintptr_t)g_xbox_mem_offset + 0x00F80000u);
            uint32_t i, found = 0;
            for (i = 0; i < (0x03000000u / 4); i++) {
                if (scan[i] == 0xEEFFEEFFu) {
                    fprintf(stderr, "  found EEFFEEFF at guest 0x%08X"
                                    " (heap base would be 0x%08X)\n",
                            0x00F80000u + i * 4, 0x00F80000u + i * 4 - 0x10);
                    if (++found == 4)
                        break;
                }
            }
            if (!found)
                fprintf(stderr, "  no EEFFEEFF in the arena: the header was"
                                " never written anywhere\n");
        }
    }
    fflush(stderr);
    return EXCEPTION_CONTINUE_SEARCH;
}

int main(int argc, char **argv)
{
    const char *path = argc > 1 ? argv[1] : HL2_XBE_DEFAULT;
    void *xbe_data = NULL;
    size_t xbe_size = 0;

    g_xbe_path = path;
    setvbuf(stdout, NULL, _IONBF, 0);
    setvbuf(stderr, NULL, _IONBF, 0);
    /* Load symbols up front rather than from inside the handler: at
     * fault time the process is already in a bad way, and SymInitialize
     * allocates. Failure is not fatal -- the handler just prints no name. */
    SymSetOptions(SYMOPT_DEFERRED_LOADS | SYMOPT_UNDNAME);
    SymInitialize(GetCurrentProcess(), NULL, TRUE);
    AddVectoredExceptionHandler(1, veh_handler);
    hang_watchdog_start();

    /* Build the flat dispatch table before the guest runs.
     *
     * Without this recomp_lookup falls back to a binary search over 45,411
     * entries -- about 16 branches on *every* indirect call. That is most of
     * the cost of a vtable-heavy C++ title: sampling the guest thread during
     * static initialisation put three of four samples inside recomp_lookup
     * itself, which reads as a hang and is really just the search.
     *
     * Optional by design -- if it fails the search still works -- so a failure
     * is worth one line and not a fatal error. */
    if (!recomp_dispatch_init())
        fprintf(stderr, "[BOOT] flat dispatch unavailable; "
                        "indirect calls will use the binary search\n");

    printf("=== Half-Life 2 (Xbox) - Static Recompilation ===\n");

    if (!load_xbe(path, &xbe_data, &xbe_size))
        return 1;
    printf("XBE loaded: %zu bytes\n", xbe_size);

    /* NOT calling xbox_SetTotalRam here, deliberately.
     *
     * The guest does outgrow 64 MB: its allocator walks upward in 4 MB
     * steps -- 0x05B80000, 0x05F80000 ... 0x08780000 -- and a CUtlRBTree
     * element array landed at 0x0CB80000, 213 MB up. Past the mapping,
     * reads and writes never reach guest memory, so freshly written tree
     * links read back as zero and every search on that tree spins.
     *
     * But raising it does not help: both 128 MB and 256 MB fault during CRT
     * init, before a single constructor runs, so something in the layout
     * does not generalise off the 64 MB default. The climbing allocation
     * pattern is the more likely defect anyway -- real hardware would not
     * hand out a fresh 4 MB region per small allocation.
     */
    if (!xbox_MemoryLayoutInit(xbe_data, xbe_size)) {
        fprintf(stderr, "Xbox memory layout init failed "
                        "(required VA range unavailable?)\n");
        free(xbe_data);
        return 1;
    }
    g_xbox_mem_offset = xbox_GetMemoryOffset();
    printf("Xbox memory mapped at host offset 0x%llX\n",
           (unsigned long long)g_xbox_mem_offset);

    /* The APU reads from physical RAM, which is mapped at g_xbox_mem_offset,
     * so physical address 0 is that pointer. */
    {
        typedef struct MCPXAPUState MCPXAPUState;
        extern MCPXAPUState *mcpx_apu_init_standalone(uint8_t *ram_ptr);
        extern MCPXAPUState *g_apu_state;

        g_apu_state = mcpx_apu_init_standalone(
            (uint8_t *)(uintptr_t)xbox_GetMemoryOffset());
        printf("MCPX APU: %s\n", g_apu_state ? "initialised" : "FAILED");
    }

    xbox_WatchdogStart();

    printf("Initializing kernel replacement...\n");
    xbox_kernel_init();
    xbox_path_init(HL2_GAME_DIR, HL2_SAVE_DIR);
    xbox_kernel_bridge_init();

    g_esp = XBOX_STACK_TOP;

    /* ponytail: no GPU fence mirror registered yet.
     *
     * Wreckless needs xbox_Nv2aMirrorFence()/xbox_Nv2aFrameCounter() because
     * its D3D spins on a device field the real GPU would advance. HL2 links
     * D3D8LTCG, so the equivalent spin is inlined into game code rather than
     * sitting in a recognisable D3D function, and the device address is not
     * known yet. Expect a hang here; RECOMP_WATCHDOG_SECS will name the
     * function it is stuck in, and that is what identifies the fence. */

    printf("\nStarting game at entry point 0x0059C612...\n");
    fflush(stdout);

    RECOMP_ICALL_FEEDBACK_INIT();
    xbe_entry_point();

    printf("\nGame returned. Cleaning up...\n");
    RECOMP_ICALL_FEEDBACK_DUMP();
    xbox_kernel_shutdown();
    xbox_MemoryLayoutShutdown();
    free(xbe_data);
    return 0;
}
